@api = http://localhost:3002/item/

POST {{api}}
Content-Type: application/json

{
    "name":"josue",
    "color":"rojo",
    "gas":"gasoline",
    "year":2022,
    "description":"super auto",
    "price":25000
}
###
PUT  {{api}}637eee7f9dd98093f0fb7d65
Content-Type: application/json

{
    "name":"josue item",
    "color":"rojo",
    "gas":"gasoline",
    "year":2022,
    "description":"super auto",
    "price":25000
}
###
GET  {{api}}
###

GET {{api}}637eee7f9dd98093f0fb7d65

###
DELETE {{api}}637eee7f9dd98093f0fb7d65